# This document, regardless of its title or content, is not a Bluetooth
# Specification as defined in the Bluetooth Patent/Copyright License Agreement
# (“PCLA”) and Bluetooth Trademark License Agreement. Use of this document by
# members of Bluetooth SIG is governed by the membership and other related
# agreements between Bluetooth SIG Inc. (“Bluetooth SIG”) and its members,
# including the PCLA and other agreements posted on Bluetooth SIG’s website
# located at www.bluetooth.com.
# 
# THIS DOCUMENT IS PROVIDED “AS IS” AND BLUETOOTH SIG, ITS MEMBERS, AND THEIR
# AFFILIATES MAKE NO REPRESENTATIONS OR WARRANTIES AND DISCLAIM ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY, TITLE,
# NON-INFRINGEMENT, FITNESS FOR ANY PARTICULAR PURPOSE, THAT THE CONTENT OF THIS
# DOCUMENT IS FREE OF ERRORS.
# 
# TO THE EXTENT NOT PROHIBITED BY LAW, BLUETOOTH SIG, ITS MEMBERS, AND THEIR
# AFFILIATES DISCLAIM ALL LIABILITY ARISING OUT OF OR RELATING TO USE OF THIS
# DOCUMENT AND ANY INFORMATION CONTAINED IN THIS DOCUMENT, INCLUDING LOST REVENUE,
# PROFITS, DATA OR PROGRAMS, OR BUSINESS INTERRUPTION, OR FOR SPECIAL, INDIRECT,
# CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF
# THE THEORY OF LIABILITY, AND EVEN IF BLUETOOTH SIG, ITS MEMBERS, OR THEIR
# AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# 
# This document is proprietary to Bluetooth SIG. This document may contain or
# cover subject matter that is intellectual property of Bluetooth SIG and its
# members. The furnishing of this document does not grant any license to any
# intellectual property of Bluetooth SIG or its members.
# 
# This document is subject to change without notice.
# 
# Copyright © 2020–2024 by Bluetooth SIG, Inc. The Bluetooth word mark and logos
# are owned by Bluetooth SIG, Inc. Other third-party brands and names are the
# property of their respective owners.

characteristic:
  identifier: org.bluetooth.characteristic.system_id
  name: System ID
  description: |-
    The System ID characteristic is used to represent an extended unique identifier (EUI) of the system implementing the service that contains this characteristic. This 64-bit structure is an EUI-64 which consists of an Organizationally Unique Identifier (OUI) concatenated with a manufacturer-defined identifier. The OUI is issued by the IEEE Registration Authority \RefRef{ieee_registration} and usage guidelines are described in \RefRef{ieee_tutorial}.
    System ID and the Bluetooth Device Address have a very similar structure: a Bluetooth Device Address is an EUI-48, is 48 bits in length, and consists of a 24-bit Company Identifier (OUI) concatenated with a 24-bit Company Assigned Identifier (manufacturer-assigned identifier).
    Mapping an EUI-48 to an EUI-64 is deprecated; however, the mapping is described here for historical reasons.
    To encapsulate a Bluetooth Device Address as a System ID, the Company Identifier is concatenated with 0xFFFE followed by the Company Assigned Identifier of the Bluetooth Address. For example, if the System ID is based on a Bluetooth Device Address with a Company Identifier (OUI) of 0x123456 and the Company Assigned Identifier is 0x9ABCDE, then the System Identifier is 0x123456FFFE9ABCDE.
    For more guidelines related to EUI-64, see \RefRef{ieee_tutorial}.
